id: P007019
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG01063
  title: བོད་ཀྱི་དགོན་སྡེའི་རིག་གནས་སྤྱི་བཤད་མེ་ཏོག་ཕྲེང་བ
  author: ''
  volumes:
    ba0bd0029a4b4abd9a7b1c1444194bd9:
      image_group_id: I1CZ910
      title: ''
      volume_number: 1
      total_pages: 183
ebook_metadata:
  title: བོད་ཀྱི་དགོན་སྡེའི་རིག་གནས་སྤྱི་བཤད་མེ་ཏོག་ཕྲེང་བ
  author: ''
  sku: P007019
  cover: cover.jpg
  layers:
  - pagination
