id: P007019
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W00KG01063
  title: བོད་ཀྱི་དགོན་སྡེའི་རིག་གནས་སྤྱི་བཤད་མེ་ཏོག་ཕྲེང་བ
  author: ''
  volumes:
    f9779cb445494324b8784cd7197d8065:
      image_group_id: I1CZ910
      title: Volume 1 of bod kyi dgon sde'i rig gnas spyi bshad me tog phreng ba
      volume_number: 1
      total_pages: 183
      base_file: v001.txt
